# ======================================================================================
# MAVROS 参数文件 | 最终权威版
#
# 结构根据 `ros2 param list` 的输出进行了精确调整，确保所有参数都能被正确加载。
# ======================================================================================
mavros: # 对应主节点 /mavros/mavros
  ros__parameters:
    # --- 飞控连接 ---
    fcu_url: "serial:///dev/ttyUSB0:921600" # ‼️ 请确认串口名和您测试成功的波特率

    # --- 坐标系名称 ---
    # 这是MAVROS节点使用的主要坐标系名称，确保与其他系统（Nav2, RTAB-Map）统一
    map_frame_id: "map"
    odom_frame_id: "odom_frame"      # ‼️ 适配T265不可修改的 "odom_frame"
    base_link_frame_id: "base_link"  # 统一使用 "base_link"

# --------------------------------------------------------------------------------------
# MAVROS 插件参数
# --------------------------------------------------------------------------------------
odometry: # 对应 /mavros/odometry 插件
  ros__parameters:
    # 告诉飞控，我们发送的里程计数据的父子坐标系是什么
    # 这是可选的，但明确指定有助于调试
    fcu:
      odom_parent_id_des: "odom_frame"
      odom_child_id_des: "base_link"

vision_pose: # 对应 /mavros/vision_pose 插件
  ros__parameters:
    tf:
      # vision_pose 插件不应该监听TF，因为它直接接收话题数据
      listen: false

# --------------------------------------------------------------------------------------
# (可选) 其他常用插件配置
# --------------------------------------------------------------------------------------
sys: # 对应 /mavros/sys 插件
  ros__parameters:
    # 设置心跳速率和超时时间
    heartbeat_rate: 1.0
    conn_timeout: 10.0