# ======================================================================================
# Nav2 参数文件 | 最终修正版 | 适用于RTAB-Map定位的无人机
#
# 该配置文件的核心思想:
# - 定位与建图: 完全由外部的 RTAB-Map 节点负责。
# - 地图服务器: Nav2 不启动 map_server，直接订阅 RTAB-Map 发布的 /map 话题。
# - 定位系统: Nav2 不启动 amcl，完全依赖 RTAB-Map 提供的 map -> odom TF变换。
# - 安全性: 移除了对无人机危险的恢复行为，并设置了保守的默认参数。
# ======================================================================================

# --------------------------------------------------------------------------------------
# Nav2 服务器配置
# --------------------------------------------------------------------------------------

controller_server:
  ros__parameters:
    use_sim_time: false # 与您的 launch 文件保持一致
    controller_frequency: 20.0

    # --- ‼️ 关键修正 1: 使用正确的插件加载参数名 ---
    # 必须使用复数形式 "plugins"
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker_plugins: ["progress_checker"]

    # --- ‼️ 关键修正 2: 明确指定当前使用的插件 ---
    # 这是解决 "No goal checker was specified" 警告的关键
    current_goal_checker: "goal_checker"
    current_progress_checker: "progress_checker"

    # --- 插件配置 ---
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 20.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.2
      stateful: true

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # --- ‼️ 关键修正 4: 启用全向移动模式 ---
      holonomic: true # 无人机是全向移动的，此项必须为true
      debug_trajectory_details: true
      
      # --- ‼️ 关键修正 5: 为全向移动开放Y轴限制并优化性能 ---
      min_vel_x: 0.0
      min_vel_y: -0.26 # 允许Y轴负向速度
      max_vel_x: 0.26
      max_vel_y: 0.26  # 允许Y轴正向速度
      max_vel_theta: 1.00
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 2.5   # 允许Y轴加速度
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: -2.5  # 允许Y轴减速度
      decel_lim_theta: -3.2
      
      # 轨迹生成参数
      # 降低采样数以适应Orange Pi的性能
      vx_samples: 10
      vy_samples: 10
      vtheta_samples: 10
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      short_circuit_trajectory_evaluation: true

      # --- ‼️ 关键修正 3: DWB 评价器必须使用正确的嵌套格式 ---
      # 这是解决 "exit code -11" (段错误) 的关键
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle:
        scale: 0.02
      PathAlign:
        scale: 32.0
        forward_point_distance: 0.1
      GoalAlign:
        scale: 24.0
        forward_point_distance: 0.1
      PathDist:
        scale: 32.0
      GoalDist:
        scale: 24.0
      RotateToGoal:
        scale: 32.0
        slowing_factor: 5.0
        lookahead_time: -1.0

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.5
      downsample_costmap: false
      allow_unknown: true

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_remove_passed_goals_action_bt_node

# --------------------------------------------------------------------------------------
# 代价地图配置 (保持不变)
# --------------------------------------------------------------------------------------

global_costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_footprint"
    use_sim_time: false
    update_frequency: 1.0
    publish_frequency: 1.0
    # footprint: "[ [0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25] ]" # 对于圆形机器人，使用 robot_radius 更佳
    robot_radius: 0.24 # 机器人半径 (m)，对应于 480mm 直径
    plugins: ["static_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.4

local_costmap:
  ros__parameters:
    global_frame: "odom"
    robot_base_frame: "base_footprint"
    use_sim_time: false
    update_frequency: 5.0
    robot_radius: 0.24 # 机器人半径 (m)，与 global_costmap 保持一致
    publish_frequency: 2.0
    width: 3
    height: 3
    resolution: 0.05
    rolling_window: true
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: depth_camera_scan
      depth_camera_scan:
        topic: "/scan"
        max_obstacle_height: 2.0
        min_obstacle_height: 0.1
        data_type: "LaserScan"
        clearing: true
        marking: true
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.4
